config/routes.rb
BolaoOnline::Application.routes.draw do
  resources :gambles

  resources :matches

  resources :teams

  resources :rounds

  resources :championships

  devise_for :users, :controllers => { :registrations => 'registrations'}

  resources :users
  

  root :to => 'home#index'
  
  match 'round_select' => 'matches#update_round_select'
  
  match 'encerrar_partidas' => 'rounds#round4_finish'
  
  match 'update_matches' => 'rounds#update_matches'
  
  match 'partidas_da_rodada' => 'matches#index'
  
  match 'apostar' => 'users#index'
  
  match 'round_classification' => 'users#round_classification'
  
  
  match 'regras' => 'home#rules'
  
  match 'finish_round_and_pontuate_users' => 'users#finish_round_and_pontuate_users'
  
  match 'set_championship_id_session' => 'championships#set_championship_id_session'

end

app/models/championship.rb
class Championship < ActiveRecord::Base
  attr_accessible :desc, :start_date, :end_date
  has_many :rounds
  has_many :participations
  has_many :users, :through => :participations

  #campos requeridos
  validates_presence_of :desc, :start_date, :end_date

end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  skip_before_filter :admin_user, :only => [:index, :show, :set_championship_id_session]

  # GET /championships
  # GET /championships.json
  def index
    @championships = Championship.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @championships }
    end
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
    @championship = Championship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @championship }
    end
  end

  # GET /championships/new
  # GET /championships/new.json
  def new
    @championship = Championship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @championship }
    end
  end

  # GET /championships/1/edit
  def edit
    @championship = Championship.find(params[:id])
  end

  # POST /championships
  # POST /championships.json
  def create
    params[:championship][:start_date] = Date.strptime(params[:championship][:start_date], '%d/%m/%Y').strftime.to_s
    params[:championship][:end_date] = Date.strptime(params[:championship][:end_date], '%d/%m/%Y').strftime.to_s
    @championship = Championship.new(params[:championship])

    respond_to do |format|
      if  @championship.save
        format.html { redirect_to championships_url, :notice =>  'Campeonato ' + @championship.desc + ' foi criado com sucesso!'  }
        format.json { render :json => @championship, :status =>  :created, :location =>  @championship }
      else
        format.html { render :action =>  "new" }
        format.json { render :json => @championship.errors, :status =>  :unprocessable_entity }
      end
    end
  end

  # PUT /championships/1
  # PUT /championships/1.json
  def update
    @championship = Championship.find(params[:id])
    params[:championship][:start_date] = Date.strptime(params[:championship][:start_date], '%d/%m/%Y').strftime.to_s
    params[:championship][:end_date] = Date.strptime(params[:championship][:end_date], '%d/%m/%Y').strftime.to_s

    respond_to do |format|
      if @championship.update_attributes(params[:championship])
        format.html { redirect_to @championship, :notice =>  'Championship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action =>  "edit" }
        format.json { render :json => @championship.errors, :status =>  :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship = Championship.find(params[:id])
    @championship.destroy

    respond_to do |format|
      format.html { redirect_to championships_url }
      format.json { head :no_content }
    end
  end
  def set_championship_id_session  
    session[:championship_id] = params[:championship][:id]
  end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_form.html.erb
<%= form_for(@championship) do |f| %>


  <% if @championship.errors.any?%>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>Foram encontrados alguns erros:</strong><br/>
      <ul>
      <% @championship.errors.each do |field, message|%>
          <li><%= "#{message}" %></li>
       <% end %>
      </ul>
    </div> 
  <% end %> 

  <div class="control-group">
    <label class="control-label" for="inputEmail">Nome: </label>
    <div class="controls">
      <%= f.text_field :desc, :placeholder => 'Nome' %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputPassword">Data Inicio Campeonato:</label>
    <div class="controls">                
      <%= f.text_field :start_date, :value => date_mdY(@championship.start_date), :class=>"ui-date-picker" %>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="inputPassword">Data Termino Campeonato:</label>
    <div class="controls">                
      <%= f.text_field :end_date, :value => date_mdY(@championship.end_date), :class=>"ui-date-picker" %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit buttonName, :class => 'btn btn-primary btn-large'%>
      <%= link_to "Voltar ", championships_path, :class => 'btn btn-primary btn-large' %>
    </div>
  </div>
<% end %>

app/views/championships/_list.html.erb
<div class="bs-docs-example">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Nome</th>
        <th>Inicio</th>
        <th>Fim</th>
      </tr>
    </thead>
    <tbody>
      <% @championships.each do |championship| %>
        <tr>
          <td><%= championship.id %></td>
          <td><%= championship.desc %></td>
          <td><%= date_mdY(championship.start_date) %></td>
          <td><%= date_mdY(championship.end_date) %></td>
          <td>
            <%= link_to championship do %>
              <i class="icon-search icon-black"></i>&nbsp;&nbsp;
            <% end %>

            <%= link_to edit_championship_path(championship)  do %>
              <i class="icon-pencil icon-black"></i>&nbsp;&nbsp;   
            <% end %>

            <%= link_to championship, :method => :delete, :data =>  { :confirm =>  'Esta certo disso? Posso deletar?' }  do %>
              <i class="icon-remove icon-black"></i>&nbsp;&nbsp;
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/championships/edit.html.erb
<h3>Editando Campeonato</h3>

<%= render 'form', :buttonName => 'Editar' %>

app/views/championships/index.html.erb
<h3>Campeonatos</h3>

<%if !notice.to_s.empty? %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <ul>   
        <li><%= notice %></li>
    </ul>
  </div>
<% end %>

<%= render 'list' %>

<hr>

<%= link_to 'Novo', new_championship_path, :class => 'btn btn-primary btn-large' %>

app/views/championships/new.html.erb
<h3>Novo Campeonato</h3>

<%= render 'form', :buttonName => 'Cadastrar' %>

app/views/championships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @championship.desc %>
</p>


<%= link_to 'Edit', edit_championship_path(@championship) %> |
<%= link_to 'Back', championships_path %>