config/routes.rb
BolaoOnline::Application.routes.draw do
  resources :gambles

  resources :matches

  resources :teams

  resources :rounds

  resources :championships

  devise_for :users, :controllers => { :registrations => 'registrations'}

  resources :users
  

  root :to => 'home#index'
  
  match 'round_select' => 'matches#update_round_select'
  
  match 'encerrar_partidas' => 'rounds#round4_finish'
  
  match 'update_matches' => 'rounds#update_matches'
  
  match 'partidas_da_rodada' => 'matches#index'
  
  match 'apostar' => 'users#index'
  
  match 'round_classification' => 'users#round_classification'
  
  
  match 'regras' => 'home#rules'
  
  match 'finish_round_and_pontuate_users' => 'users#finish_round_and_pontuate_users'
  
  match 'set_championship_id_session' => 'championships#set_championship_id_session'

end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :championship
  has_many :matches
  attr_accessible :desc, :num_round, :start_date, :end_date

  validates_presence_of :start_date, :end_date, :message => "sdasd"

  def self.current_round(championship_id) 
    where("championship_id = ? and num_round = ? ",[championship_id], [Round.maximum(:num_round)]).limit(1).first
  end
  
  def finish_round_and_pontuate_users#(championship_id = nil)
    #if championship_id == nil
    #  championship_id = Championship.where("championships.desc = 'Campeonato Brasileiro'").first.id
    #end
    matches.each do|m|
      m.gambles.each do |g|
        g.user_points = g.points4_user
        g.save
        if g.user.participations != nil
           p = g.user.participations.find_by_championship_id(championship.id)
           p.user_points = (p.user_points == nil)? g.user_points : p.user_points + g.points4_user
           p.save
        end
      end
    m.save
    end        
  end  
  
  def self.get_all_rounds_by_championship_id(championship_id, page = nil)
    joins(:championship).where("rounds.championship_id = ? ", [championship_id]).paginate(:page => page, :per_page => 1)  
  end
  #scope :last_round, where("num_round = ? and championship_id = ? ",[Round.maximum(:num_round)], [championship.id])
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  skip_before_filter :admin_user, :only => [:index, :show]
  # GET /rounds
  # GET /rounds.json
  def index
    championship = Championship.find_by_desc($current_championship)
    unless championship == nil?
      @rounds = Round.get_all_rounds_by_championship_id(championship.id, params[:page])
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json =>  @rounds }
    end
  end

  # GET /rounds/1
  # GET /rounds/1.json
  def show
    @round = Round.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json =>  @round }
    end
  end

  # GET /rounds/new
  # GET /rounds/new.json
  def new
    @championships = Championship.all
    @round = Round.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json =>  @round }
    end
  end

  # GET /rounds/1/edit
  def edit
    @round = Round.find(params[:id])
  end

  # POST /rounds
  # POST /rounds.json
  def create
    @round = Round.new(params[:round])
    params[:round][:start_date] = Date.strptime(params[:round][:start_date], '%d/%m/%Y').strftime.to_s
    params[:round][:end_date] = Date.strptime(params[:round][:end_date], '%d/%m/%Y').strftime.to_s

    if params[:championship][:championship_id] == ""
      respond_to do |format|
        flash[:error] = "Voce deve selecionar o campeonato"
        format.html { render :action =>  "new" }
      end
    else
      @championship = Championship.find(params[:championship][:championship_id])
      @last_round4_championship = Round.find_by_championship_id(@championship.id)
      @round.championship = @championship
      num_round = (@last_round4_championship == nil)? 1 : Round.maximum(:num_round) +1
      @round.num_round = num_round


      respond_to do |format|
        if @round.save
          format.html { redirect_to @round, :notice =>  'Round was successfully created.' }
          format.json { render :json =>  @round, :status =>  :created, :location =>  @round }
        else
          format.html { render :action =>  "new" }
          format.json { render :json =>  @round.errors, :status =>  :unprocessable_entity }
        end
      end
    end
  end

  # PUT /rounds/1
  # PUT /rounds/1.json
  def update
    @round = Round.find(params[:id])
    params[:round][:start_date] = Date.strptime(params[:round][:start_date], '%d/%m/%Y').strftime.to_s
    params[:round][:end_date] = Date.strptime(params[:round][:end_date], '%d/%m/%Y').strftime.to_s

    respond_to do |format|
      if @round.update_attributes(params[:round])
        format.html { redirect_to @round, :notice =>  'Round was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action =>  "edit" }
        format.json { render :json =>  @round.errors, :status =>  :unprocessable_entity }
      end
    end
  end

  # DELETE /rounds/1
  # DELETE /rounds/1.json
  def destroy
    @round = Round.find(params[:id])
    @round.destroy

    respond_to do |format|
      format.html { redirect_to rounds_url }
      format.json { head :no_content }
    end
  end
  
  def round4_finish
    @matches = Match.last_round_matches
    @round = @matches.first.round if (@matches.present?) and (@matches.first.round != nil)
  end
  
  def update_matches
    Match.update_all_matches(params[:round][:matches_attributes])
    redirect_to encerrar_partidas_path
    flash[:notice] = "Partidas atualizadas com sucesso!"
      #puts "ID = " + m[0].to_s
      #puts "Gols time 1 = " + m[1]["goals_team1"].to_s
      #puts "Gols time 2 = " + m[1]["goals_team2"].to_s      
    #end
    #match = Match.find()
    #Match.update_all(params[:round][:matches_attributes])
  end
  def num_round_select
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/_form.html.erb
<%= form_for(@round) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if flash[:error] %>
      <div class="alert">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <strong>Um erro foi encontrado</strong><br/>
      <ul>
     <li><%= flash[:error] %></li>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descrição %>
    <%= f.text_field :desc  %>
  </div>
  <div class="field">
    <%= select_tag "championship[championship_id]", options_from_collection_for_select(@championships,"id","desc"), :prompt => "Selecione o campeonato" %> 
  </div>
    <div class="field">
    <%= f.label :data_inicio %>
    <%= f.text_field :start_date, :class =>"ui-date-picker"  %>
  </div>
    <div class="field">
    <%= f.label :data_fim %>
    <%= f.text_field :end_date, :class =>"ui-date-picker"  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rounds/edit.html.erb
<h1>Editing round</h1>

<%= render 'form' %>

<%= link_to 'Show', @round %> |
<%= link_to 'Back', rounds_path %>

app/views/rounds/index.html.erb
<div class="flickr_pagination">
    <%= will_paginate @rounds, :previous_label => '← Anterior', :next_label => 'Próximo →', :container => false %>
</div>
<% unless @rounds == nil %>
	<div class="bs-docs-grid">
	<% @rounds.each do |round| %>
	    <h2 style="font-size:30px; color:#6495ED;margin-left:20%; text-align:center;">Resultados da <%= round.num_round.to_s %>º Rodada do <%= round.championship.desc%></h2>
		<br/>	
		<% unless (round.matches == nil) or (round.matches.count == 0 )%>
			<% round.matches.each do |match| %>
			    <div class="row-fluid show-grid">
				  <div class="span1" style="margin:0 10px 0 0"><%= link_to (image_tag match.team1.image.url(:thumb)), match.team1, :class =>'basic-link' %></div>
				  <% unless match.goals_team1 == nil %>
				    <div class="span1" style="font-size:40px;margin:23px -30px 0 10px"><%= match.goals_team1 %></div>
				  <% end %>
			      <div class="span1 span-versus"><%= image_tag ('versus.gif') %></div>
				  <% unless match.goals_team2 == nil %>
				    <div class="span1" style="font-size:40px;margin:23px -30px 0 10px"><%= match.goals_team2 %></div>
				  <% end %>
			      <div class="span1"><%= image_tag match.team2.image.url(:thumb), :alt => match.team2.name %></div>
				   <div class="span4 span-date"><%= standart_date(match.date_match, "/") %></div>
			    </div>
				<div class="article_seperator sep-teams"></div>
			<br/>
			<br/>
			<% end %>
		<% else %>
		  	<h3>Ainda não há partidas cadastradas para a <%= round.num_round %>º rodada</h3>
		<% end %>
	<% end %>	
	</div>
	<br />
<% else %>
  	<h2>Pô cara ainda não há partidas cadastradas para a próxima rodada, espera aí Jiow blz?...</h2>
<% end %>

app/views/rounds/new.html.erb
<h1>Nova Rodada</h1>

<%= render 'form' %>

<%= link_to 'Back', rounds_path %>

app/views/rounds/round4_finish.html.erb
<br/>
<br/>
<% unless @round == nil %>
	<%= form_for :round, :url=> update_matches_path do |f| %>
		<h2 style="font-size:30px; color:#6495ED;margin-left:20%;"><%= @round.num_round %>º Rodada do <%= @round.championship.desc%></h2>
		<% for match in @round.matches %>
		  <%= fields_for "round[matches_attributes][]", match do |match_form| %>
			<div class="row-fluid show-grid">
				<div class="span1"><%= match_form.text_field :goals_team1, :class => "goals_input",:style=>"height:40px;font-size:20px;text-align:center;"%></div>			
				<div class="span1"><%= link_to (image_tag match.team1.image.url(:thumb)), match.team1, :class =>'basic-link', :alt => match.team1.name %></div>			
				<div class="span1 span-versus"><%= image_tag ('versus.gif') %></div>
				<div class="span1"><%= image_tag match.team2.image.url(:thumb), :alt => match.team2.name %></div>
				<div class="span1"><%= match_form.text_field :goals_team2, :class => "goals_input", :style=>"height:40px;font-size:20px;text-align:center;"%></div>
			</div>
			<br/>
		  <% end %>
		<% end %>
		<%= submit_tag "Atualizar partidas", :class=>"btn btn-danger" %>
	<% end %>
	<% if flash[:notice]  %>
	<div class="alert">
	   <button type="button" class="close" data-dismiss="alert">×</button>
	   <strong><%= flash[:notice] %></strong><br/>
	</div>
	<% end %>
<% else %>
<strong>Ainda não foram cadastradas partidas!</strong>
<% end %>

app/views/rounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rodada atual:</b>
  <%= @round.num_round %>
</p>

<p>
  <b>Desc:</b>
  <%= @round.desc %>
</p>

<p>
  <b>Campeonato:</b>
  <%= @round.championship.desc %>
</p>


<%= link_to 'Edit', edit_round_path(@round) %> |
<%= link_to 'Back', rounds_path %>