config/routes.rb
BolaoOnline::Application.routes.draw do
  resources :gambles

  resources :matches

  resources :teams

  resources :rounds

  resources :championships

  devise_for :users, :controllers => { :registrations => 'registrations'}

  resources :users
  

  root :to => 'home#index'
  
  match 'round_select' => 'matches#update_round_select'
  
  match 'encerrar_partidas' => 'rounds#round4_finish'
  
  match 'update_matches' => 'rounds#update_matches'
  
  match 'partidas_da_rodada' => 'matches#index'
  
  match 'apostar' => 'users#index'
  
  match 'round_classification' => 'users#round_classification'
  
  
  match 'regras' => 'home#rules'
  
  match 'finish_round_and_pontuate_users' => 'users#finish_round_and_pontuate_users'
  
  match 'set_championship_id_session' => 'championships#set_championship_id_session'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :round
  attr_accessible :date_match, :goals_team1, :goals_team2, :team1, :team2
  belongs_to :team1, :class_name => Team, :foreign_key => 'team_1_id'
  belongs_to :team2, :class_name => "Team", :foreign_key => 'team_2_id'
  has_many :gambles
  
  #obtem todas as partidas da última rodada
  def self.last_round_matches(page = nil)
    joins(:round).where("num_round = ?",[Round.maximum(:num_round)]).order('date_match ASC').paginate(:page => page, :per_page => 4 ) 
  end
  #obtém as partidas após determinada data
  def self.matches_after_date (date, page = nil)
    where("date_match >= ?", [date]).paginate(:page => page, :per_page => 4 )
    #where("date_match >= ?", [date]).paginate(:page => page, :per_page => 4 ).order('date_match ASC')
  end
  #obtém as partidas da última rodada associadas a um time
  #def self.user_matches4_last_round(user_team)
  #  joins(:round).where("(team_1_id = #{user_team} or team_2_id = #{user_team}) and num_round = #{Round.maximum(:num_round)}")
  #end
  def self.user_matches4_last_round(user_team)
    unless Round.maximum(:num_round) == nil
      joins(:round).where("(team_1_id = #{user_team} or team_2_id = #{user_team}) and num_round = #{Round.maximum(:num_round)}")
    else
      nil
    end
  end
  def self.user_matches(user_team)
    where("(team_1_id = #{user_team} or team_2_id = #{user_team}) and date_match >= '#{ApplicationHelper.get_utc_time}'").order("date_match DESC")
  end  
  #Atualiza todas as apostas (Matches) vindas da tela ""round4_finish".
  def self.update_all_matches(matches)
    matches.each do |m|
      match4_update = Match.find(m[0].to_i)      
      match4_update.goals_team1 = (m[1]["goals_team1"].to_s.eql? "")? nil : m[1]["goals_team1"].to_i
      match4_update.goals_team2 = (m[1]["goals_team2"].to_s.eql? "")? nil : m[1]["goals_team2"].to_i
      match4_update.save
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  skip_before_filter :admin_user

  def update_round_select
    @current_round = Round.current_round(params[:championship][:id].to_s)
    respond_to do |format|
      format.js
    end
  end
  # GET /matches
  # GET /matches.json
  def index
    #@matches = Match.all
    #@matches = Match.matches_after_date(ApplicationHelper.get_utc_time, params[:page])
    @matches = Match.last_round_matches(params[:page])
    @num_round = (@matches.present?)? @matches.first.round.num_round : nil
    @teams = Team.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json =>  @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json =>  @match }
    end
  end

  # GET /matches/new
  # GET /matches/new.json
  def new
    @match = Match.new
    @teams = Team.all
    @championships = Championship.all
    @current_round = (@championships == nil)? nil: Round.current_round(@championships.first.id)    
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json =>  @match }
    end
  end

  # GET /matches/1/edit
  def edit
    @match = Match.find(params[:id])
  end

  # POST /matches
  # POST /matches.json
  def create
    #puts "o round " + params[:round_id]
    @match = Match.new(params[:match])
    @team = Team.find(params[:team1][:id])
    @match.team1 = @team    
    @team = Team.find(params[:team2][:id])
    @match.team2 = @team
    @match.round = Round.find(params[:round_id])

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, :notice =>  'Match was successfully created.' }
        format.json { render :json =>  @match, :status =>  :created, :location =>  @match }
      else
        format.html { render :action =>  "new" }
        format.json { render :json =>  @match.errors, :status =>  :unprocessable_entity }
      end
    end
  end

  # PUT /matches/1
  # PUT /matches/1.json
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to @match, :notice =>  'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action =>  "edit" }
        format.json { render :json =>  @match.errors, :status =>  :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> encontrados:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Time_1 %><br />
    <%= collection_select  :team1, :id, @teams, :id, :name, :prompt => true , :placeholder =>'Escolha seu time' %>
  </div>
  <div class="field">
    <%= f.label :Time_2 %><br />
    <%= collection_select  :team2, :id, @teams, :id, :name, :prompt => true , :placeholder =>'Escolha seu time' %>
  </div>
  <div class="field">
    <%= f.label :date_match, "Data da Partida" %><br />
    <%= f.text_field :date_match, :class=>"ui-date-time-picker"	%>
  </div>
  <div class="field">
	<% if @championships.present? %>
      <div class="controls">
	     <%= f.label :campeonato %>
      </div>  
     <div class="controls" >
	 	<%= select_tag "championship[championship_id]", options_from_collection_for_select(@championships,"id","desc"), 
	       :onchange => "$.post('#{round_select_path}', {'_method':'get', 'championship[id]':this.value} );" %> 
	</div>  
      <% else %>
        Cadastre um novo campeonato
      <% end%>
  </div>
  <div id="select_round_div">
  	<%= render 'select_round', :locals=>{:current_round => @current_round} %>
  </div>
  <div class="actions">
    <%= f.submit 'Criar partida', :class => "btn" %>
  </div>
<% end %>

app/views/matches/_matches.erb
<% unless @num_round == nil %>
	<h2 style="font-size:30px; color:#6495ED;margin-left:20%;"><%= @num_round.to_s %>º Rodada do <%=@matches.first.round.championship.desc%></h2>
	<br/>
	<div class="bs-docs-grid">

	<% @matches.each do |match| %>
	    <div class="row-fluid show-grid">
		  <div class="span1" style="margin:0 10px 0 0"><%= link_to (image_tag match.team1.image.url(:thumb)), match.team1, :class =>'basic-link' %></div>
		  <% unless match.goals_team1 == nil %>
		    <div class="span1" style="font-size:40px;margin:23px -30px 0 10px"><%= match.goals_team1 %></div>
		  <% end %>
	      <div class="span1 span-versus"><%= image_tag ('versus.gif') %></div>
		  <% unless match.goals_team2 == nil %>
		    <div class="span1" style="font-size:40px;margin:23px -30px 0 10px"><%= match.goals_team2 %></div>
		  <% end %>
	      <div class="span1"><%= image_tag match.team2.image.url(:thumb), :alt => match.team2.name %></div>
		   <div class="span4 span-date"><%= standart_date(match.date_match, "/") %></div>
	    </div>
		<div class="article_seperator sep-teams"></div>
	<br/>
	<br/>
	<% end %>

	<div class="flickr_pagination">
	    <%= will_paginate @matches, :previous_label => '← Anterior', :next_label => 'Próximo →', :container => false %>
	</div>
	</div>
	<br />
<% else %>
  	<h2>Pô cara ainda não há partidas cadastradas para a próxima rodada, espera aí Jiow blz?...</h2>
<% end %>

app/views/matches/_select_round.erb
<div class="field">
	<% if @current_round != nil %>
      <h3><%= "Rodada atual: " + @current_round.num_round.to_s %></h3>
      <%= hidden_field_tag "round_id", @current_round.id %>
    <% else %>
      <h3>Cadastre uma nova rodada</h3>
	  <%= hidden_field_tag "round_id", "" %>      
    <% end%>
</div>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<%= render 'matches'%>

app/views/matches/new.html.erb
<h1>Nova partida</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Team 1:</b>
  <%= @match.team1 %>
</p>

<p>
  <b>Team 2:</b>
  <%= @match.team2 %>
</p>

<p>
  <b>Goals team 1:</b>
  <%= @match.goals_team1 %>
</p>

<p>
  <b>Goals team 2:</b>
  <%= @match.goals_team2 %>
</p>

<p>
  <b>Date match:</b>
  <%= @match.date_match %>
</p>

<p>
  <b>Round:</b>
  <%= @match.round %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>

app/views/matches/update_round_select.js.erb
//$("#round_id").html('');
$("#select_round_div").html("<%= escape_javascript(render 'select_round', :current_round => @current_round) %>");