config/routes.rb
BolaoOnline::Application.routes.draw do
  resources :gambles

  resources :matches

  resources :teams

  resources :rounds

  resources :championships

  devise_for :users, :controllers => { :registrations => 'registrations'}

  resources :users
  

  root :to => 'home#index'
  
  match 'round_select' => 'matches#update_round_select'
  
  match 'encerrar_partidas' => 'rounds#round4_finish'
  
  match 'update_matches' => 'rounds#update_matches'
  
  match 'partidas_da_rodada' => 'matches#index'
  
  match 'apostar' => 'users#index'
  
  match 'round_classification' => 'users#round_classification'
  
  
  match 'regras' => 'home#rules'
  
  match 'finish_round_and_pontuate_users' => 'users#finish_round_and_pontuate_users'
  
  match 'set_championship_id_session' => 'championships#set_championship_id_session'

end

app/views/layouts/_menu.html.erb
<% if user_signed_in? %>
  <div class="header content">
	 <div class="championship-div">
		<span>
		<%= select_tag "championship[championship_id]", options_from_collection_for_select(@championships,"id","desc", :selected => session[:championship_id]), 
		   :onchange => "$.post('#{set_championship_id_session_path}', {'_method':'get', 'championship[id]':this.value} );" %>
		</span>	 
	 </div>
      <div class="menu">
          <ul class="nav nav-pills pull-right ">
            <li class="<%= 'active' if current_page?(apostar_path) %>">
                  <%= link_to "Apostar", apostar_path %>
            </li> 
	          <li class="<%= 'active' if current_page?(partidas_da_rodada_path) %>">
                  <%= link_to "Partidas", partidas_da_rodada_path %>
              </li>
              <li class="<%= 'active' if current_page?(rounds_path) %>">
                  <%= link_to "Rodadas", rounds_path %>
              </li>
   
              <!-- Este menu é para os usuarios administradores do sistema, ou seja os high levels -->        
              <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">                  
                  Administração <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                      <li>
                         <%= link_to "Campeonatos", championships_path %>
                      </li>
                      <li>
                         <%= link_to "Rodadas", rounds_path %>
                      </li>                     
                      <li>
                         <%= link_to "Partidas", matches_path %>
                      </li>
                      <li>                        
                        <%= link_to "Times", teams_path %>
                      </li>
                      <li>
                         <%= link_to "Apostar", apostar_path %>
                      </li>
                      <li>
                        <%= link_to "Apostadores", gambles_path %>
                      </li>
                      <li>
                         <%= link_to "Encerrar", encerrar_partidas_path %>
                      </li>
                  </ul>
              </li>
              <!-- Fim do menu dos high levels -->        

              <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <i class="icon-user icon-black"></i>&nbsp;&nbsp;
                  <%= current_user.name %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                      <li>
                        <%= link_to(edit_user_path(current_user)) do %><i class="icon-pencil icon-black"></i>&nbsp;&nbsp; Editar Perfil<% end %>
                      </li>
                      <li>
                        <%= link_to(current_user) do %><i class="icon-star icon-black"></i>&nbsp;&nbsp; Campeonatos<% end %>
                      </li>
                      <li>
                        <%= link_to(current_user) do %><i class="icon-calendar icon-black"></i>&nbsp;&nbsp; Historico Apostas    <% end %>
                      </li>
                      <li class="divider"></li>
                      <li>
                        <%= link_to(destroy_user_session_path, :confirm => "nbad") do %>
					                <i class="icon-off icon-black"></i>&nbsp;&nbsp; Log Out
				                <% end %>
                      </li>                      
                  </ul>
              </li>
          </ul>
      </div>
  </div>
<% end %>

app/views/layouts/_userInfo.html.erb
<div class="thumbnail" style="border: 1px solid black;">
    <%= link_to (image_tag current_user.image.url(:thumb), :alt => current_user.name), current_user %>
</div>
<div class="caption">     
    <blockquote>
      <h4>
        <center>
          <%= current_user.name.humanize %>
        </center>
      </h4>        
      <% if current_user.teams.first == nil %>      
        <small>Oh meu amigo escolhe um time aí <%= link_to 'Clique aqui', edit_user_path(current_user) %> </small>
      <% else %>  
        <%= image_tag current_user.teams.first.image.url(:thumb) %>
        <%= current_user.teams.first.description %> 
      <% end %>
    </blockquote>
</div>
<hr style="border-bottom: 1px solid black;" />
<div>
	<%= render "users/ranking", :locals => {:users_by_championship_classification => @users_by_championship_classification} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Bolão duBah Jiow!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag "docs" %>
  <%= stylesheet_link_tag "jquery.countdown.css"%>
  <%= stylesheet_link_tag "jquery-ui-sliderAccess" %> 
  <%= stylesheet_link_tag "jquery-ui-timepicker-addon.js" %>   

  <%= csrf_meta_tags %>
</head>
  <body>    
    <div class="bolaodubah-header-bar" style="overflow: inherit;">
        <div class="header content">            
            <%= link_to (image_tag "logo.gif") , root_path, :class => 'logo' %>
        </div>
        <%= render 'layouts/menu' %>    
    </div>    
    <br/>
    <% if user_signed_in? %>   
      <div class="container-fluid">
        <div class="row">
            <div class="span3 offset1" id="user_Info_ranking">
                <%= render 'layouts/userInfo' %>
            </div>
            <div class="span9">
                <div class="row">
                    <div class="span12">
                        <div class="hero-unit">
                            <%= yield %>                            
                            <% if current_user.email == "marclameu@gmail.com" %>
                              <%= link_to 'Classificar Usuários', round_classification_path %>
                            <%end%>
                        </div>
                    </div>
                </div>                
            </div>
        </div>
    <% else %>
      <%= yield %>
    <%end%>
    <hr>
    <footer>
        <center>
        <p>&copy; STARTAR Tecnologia 2012</p>
        </center>
    </footer>
  </body>
  <%= javascript_include_tag :defaults %> 
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.countdown" %>
</html>